language: php

matrix:
    include:
        - php: 5.5
        - php: 5.6
        - php: hhvm
        - php: nightly

before_script:
  - travis_retry composer self-update
  - travis_retry composer install --no-interaction --prefer-source --dev

script:
  - vendor/bin/phpunit --verbose --coverage-text
